version: "3.8"

services:
  fe_nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/fe-nextjs
      - /fe-nextjs/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
